services:
  gta:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - PORT=5000
      - REFRESH_INTERVAL=${REFRESH_INTERVAL:-300}
      - RATE_LIMIT=${RATE_LIMIT:-100 per minute}
      - BASE_URL=gta.tamton.dev
    restart: unless-stopped
